name: Release

on:
  push:
    tags: [ 'v*' ]


jobs:
  release:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Unshallow
      run: git fetch --prune --unshallow

    - name: Install goreleaser
      run: |
        curl -sfL https://install.goreleaser.com/github.com/goreleaser/goreleaser.sh | sudo bash -s -- -b /usr/local/bin

    - name: Install github-release-notes
      env:
        GH_REL_URL: https://github.com/buchanae/github-release-notes/releases/download/0.2.0/github-release-notes-linux-amd64-0.2.0.tar.gz
      run: |
        cd /tmp && curl -sSL ${GH_REL_URL} | tar xz && sudo mv github-release-notes /usr/local/bin/

    - name: Generate release notes
      run: |
        IFS='/'
        read -a arr <<< "$GITHUB_REPOSITORY"
        ORGANISATION="${arr[0]}"
        REPO="${arr[1]}"
        echo 'CHANGELOG' > /tmp/release.txt
        github-release-notes -org "$ORGANISATION" -repo "$REPO" -since-latest-release -include-author >> /tmp/release.txt
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Release
      run: |
        goreleaser release --release-notes=/tmp/release.txt
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

